# Generated by Django 6.0.3 on 2026-04-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='No Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
    ]
