# Generated by Django 6.0.3 on 2026-05-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0002_alter_student_full_name_alter_student_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_location',
            field=models.CharField(default='Office of the Adviser', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='requester_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='event_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='equipment_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Pending Adviser', 'Pending Adviser Approval'), ('Pending Admin', 'Pending Admin Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Adviser', max_length=50),
        ),
    ]
