# Generated by Django 6.0.3 on 2026-05-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0003_event_current_location_event_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='letter_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='permit_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_documents/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Pending Adviser', 'Pending Adviser Approval'), ('Pending Admin', 'Pending Admin Initial Clearance'), ('Admin Approved', 'Admin Approved (Awaiting Documents)'), ('Permit Verification', 'Permit Verification (Adviser)'), ('Final Admin Review', 'Final Admin Review'), ('Approved', 'Approved / Published'), ('Rejected', 'Rejected')], default='Pending Adviser', max_length=50),
        ),
    ]
