# Generated by Django 6.0.3 on 2026-05-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0004_event_letter_image_event_permit_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='equipment_needed',
        ),
        migrations.AddField(
            model_name='event',
            name='adviser_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
