# Generated by Django 6.0.3 on 2026-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0005_remove_event_equipment_needed_event_adviser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='equipment_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_documents/'),
        ),
    ]
