# Generated by Django 6.0.3 on 2026-05-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0007_loginlockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
