# Generated by Django 6.0.3 on 2026-05-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0008_student_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='other_attachments',
            field=models.ImageField(blank=True, null=True, upload_to='event_documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='requirement_mode',
            field=models.IntegerField(blank=True, choices=[(2, '2 Documents'), (4, '4 Documents')], null=True),
        ),
    ]
