# Generated by Django 6.0.3 on 2026-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0009_event_other_attachments_event_requirement_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='reschedule_cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_documents/'),
        ),
    ]
