# Generated by Django 6.0.3 on 2026-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0010_event_cover_photo_event_reschedule_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='excuse_letter_equipment',
            field=models.ImageField(blank=True, null=True, upload_to='event_documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='letter_of_approval',
            field=models.ImageField(blank=True, null=True, upload_to='event_documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='letter_of_reschedule',
            field=models.ImageField(blank=True, null=True, upload_to='event_documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='permit_to_conduct',
            field=models.ImageField(blank=True, null=True, upload_to='event_documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='reschedule_cover_photo_legacy',
            field=models.ImageField(blank=True, null=True, upload_to='event_documents/'),
        ),
    ]
