# Generated by Django 6.0.3 on 2026-05-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0011_event_event_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
