# Generated by Django 6.0.3 on 2026-06-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0013_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAILED', 'Failed Login'), ('LOGOUT', 'Logout'), ('UNAUTHORIZED', 'Unauthorized Access Attempt'), ('SYSTEM_ERROR', 'System Error'), ('FILE_UPLOAD', 'File Uploaded'), ('STATUS_CHANGE', 'Approval Status Change'), ('ATTENDANCE', 'Attendance Recorded'), ('EVALUATION', 'Evaluation Submitted'), ('REGISTRATION', 'Account Registered'), ('VERIFICATION', 'Account Verified')], max_length=50),
        ),
    ]
