# Generated by Django 6.0.3 on 2026-06-04 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0014_orgprofile_face_encoding_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus_app.orgprofile'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus_app.student'),
        ),
    ]
