# Generated by Django 6.0.3 on 2026-06-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0016_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_valid_location_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='latitude_out',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude_out',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
