# Generated by Django 6.0.3 on 2026-06-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0017_attendance_is_valid_location_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='capture_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_captures/'),
        ),
    ]
