# Generated by Django 6.0.3 on 2026-06-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0018_attendance_capture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='location_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
