# Generated by Django 6.0.3 on 2026-06-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0019_attendance_location_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_flag_raising',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
