# Generated by Django 6.0.3 on 2026-06-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0020_event_is_flag_raising_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='read_notifications',
            field=models.TextField(blank=True, default=''),
        ),
    ]
