# Generated by Django 6.0.3 on 2026-06-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0021_orgprofile_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='capture_image_out',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_captures/'),
        ),
    ]
