# Generated by Django 6.0.3 on 2026-10-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0022_attendance_capture_image_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='year_level',
            field=models.CharField(default='1st Year', max_length=20),
        ),
    ]
