# Generated by Django 6.0.3 on 2026-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0023_orgprofile_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
