# Generated by Django 6.0.3 on 2026-10-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_app', '0024_orgprofile_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
